### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by GayathriMadala** [Prisma-pResearch/ic3-online-documentation#3]
Tasks 
Date: Mar 20, 2024
DDL: April 15th, 2024

@GayathriMadala 
- [ ] Fix Justification in all phases, Upload clear Flowcharts and move flowcharts to the top 
- [ ] Complete Phase5 Edits
- [ ] Add Coordinator Phase and Seperate files from Phase 1

<img width="1054" alt="navbar redesign" src="https://github.com/Prisma-pResearch/ic3-online-documentation/assets/34854131/3c800b59-e4e4-48bc-81ae-125444af9c77">

@rl-zhu 
- [ ] Redesign the home page
- [ ] Update the nav bar
- [ ] Update the version as well as dependencies

**Comment by GayathriMadala** [comment]
Completed these two tasks

**Comment by Chesterguan** [comment]
@rl-zhu  
Hi Ruilin, thanks for the updating of the navBar and upgrades to v3.

Here are some minor changes I want you to make quickly:

1. change `forum` to `Discussion` 
2. Dataset's sidebar is not generated correctly, need to create
3. The landing page needs to modify as we discussed

Please keep updating, thanks!

**Comment by rl-zhu** [comment]
<img width="969" alt="Screenshot 2024-06-20 at 4 45 49 PM" src="https://github.com/Prisma-pResearch/ic3-online-documentation/assets/98198477/7bfd0e70-da84-45d4-950a-44af9be7278a">

## Website Design Document

### Navigation Bar
- **Left**
  - Icon
  - Dataset
  - Resources
  - Project
- **Right**
  - [ Search Box ]
  - Discussion
### Footer
- Add info and necessary links to it

### Dataset

#### Dashboard
- Overview of the database, featuring cards that display key parameters such as:
  - Number of patients
  - Time range
  - Last updated time

#### Datasets
- Detailed information on each dataset, including:
  - Visualizations of general data (pie charts, line graphs, bar charts, etc.)
  - Access tutorials
  - Table dictionary to help users understand the function of each table

#### ETL Process
- Phase 1 ~ 5 codes and tutorials

#### OMOP Summary
- Tutorials
- Concise introductions and links for OMOP of each project

### Resources

#### Resource List
- Tutorials for accessing databases and servers
- Cards displaying server parameters

#### Models
- Information and resources related to different models

#### Resource Links
- A collection of links to various resources and tutorials

### Projects
#### General Intro of each projects 
- link to them

#### Project 1
- Documents
- Links
- Codes
- Publications
